# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("item.proto", :syntax => :proto3) do
    add_message "Item" do
      optional :title, :string, 1
    end
  end
end

Item = Google::Protobuf::DescriptorPool.generated_pool.lookup("Item").msgclass
