# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: item.proto for package ''

require 'grpc'
require 'item_pb'

module ItemService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'ItemService'

    rpc :GetItems, Item, Item
  end

  Stub = Service.rpc_stub_class
end
