# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: list.proto for package ''

require 'grpc'
require 'list_pb'

module ListService
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'ListService'

    rpc :GetLists, List, List
  end

  Stub = Service.rpc_stub_class
end
