# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: list.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("list.proto", :syntax => :proto3) do
    add_message "List" do
      optional :title, :string, 1
    end
  end
end

List = Google::Protobuf::DescriptorPool.generated_pool.lookup("List").msgclass
